name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Log in to Docker Hub
      run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      env:
        DOCKER_USER: ${{ vars.DOCKER_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_HOST: "docker.io"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAMESPACE/$IMAGE_REPOSITORY:$IMAGE_TAG
      env:
        IMAGE_NAMESPACE: ${{ vars.DOCKER_USERNAME }}
        IMAGE_REPOSITORY: ${{ vars.IMAGE_REPOSITORY }}
        IMAGE_TAG: "v1.0.0" # Will need a better solution

    - name: Push the Docker image
      run: docker push $IMAGE_NAMESPACE/$IMAGE_REPOSITORY:$IMAGE_TAG
      env:
        IMAGE_NAMESPACE: ${{ vars.DOCKER_USERNAME }}
        IMAGE_REPOSITORY: ${{ vars.IMAGE_REPOSITORY }}
        IMAGE_TAG: "v1.0.0" # Will need a better solution